Including cme standard copyright
Stanford-Online/cme-theme pull request #7
Opened 2016-09-26 16:43 UTC by diegomillan

## [CME2](https://docs.google.com/document/d/1q4M39uZW2M27nyPYAKKIewp4Xj5lffEdhoddVIzdNFE/edit?ts=57d2edbe#bookmark=id.dqrm8x3q1i9j)

### Description

This PR is a theme customization in order to include a standard copyright footer at the bottom of the page under the Unit Navigation.
Basically,  a `license.html` template was created with required changes.This template dynamically calculate the current year, so there is no need to modify them in the future. 

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.

- [ ] Code review: @stvstnfrd
- [ ] Code review: @felipemontoya

FYI: Tag anyone who might be interested in this PR here

@juancamilom

### Post-review
- [ ] Rebase and squash commits

2016-09-29 16:36 UTC, felipemontoya commented
This is ready for the @stvstnfrd review. :+1: from me.

2016-10-04 00:18 UTC, stvstnfrd commented
@diegomillan @felipemontoya 

This looks like you're just using the standard licenscing feature,
but forking the template? A couple of thoughts.
- When I originally suggested, "do this in a theme", it's because I
  thought Mark wanted the footer on _every_ _single_ page, not just
  courseware pages.
- The former wasn't possible with the licensing feature, hence my
  suggestion.
- This looks like Mark just wants the latter (good, it's more
  maintainable). In that case, theming is overkill, let's just enable
  licensing and call it a day.

2016-10-14 15:48 UTC, diegomillan commented
Hi @stvstnfrd we have updated this PR according to Mark's feedback. He would like to have the copyright on every LMS page and not just inside the course. Note we made changes only to the CME theme.

We are ready for your feedback here, thanks.

2016-10-17 21:07 UTC, stvstnfrd requested changes
Some small comments, but otherwise looking good.

> He would like to have the copyright on every LMS page and not just inside the course.

Glad we confirmed :)

2016-10-17 21:07 UTC, stvstnfrd commented on templates/theme-footer.html
> +        © ${now().strftime('%Y')} <span class="license-text">${_("Stanford Medicine")}</span>
Lets use the `&copy;` htmlentity here, instead of directly embedding the symbol.

2016-10-17 21:07 UTC, stvstnfrd commented on templates/theme-footer.html
> +        © ${now().strftime('%Y')} <span class="license-text">${_("Stanford Medicine")}</span>
`&copy; 20XX` should be wrapped in a `SPAN` tag, as text shouldn't appear immediately within a blocklevel element

2016-10-17 21:07 UTC, stvstnfrd commented on templates/theme-footer.html
> +        © ${now().strftime('%Y')} <span class="license-text">${_("Stanford Medicine")}</span>
For consistency in Python/JS, we use single quotes for non-interpolated strings; `$(_('Stanford Medicine'))`.

2016-10-17 21:31 UTC, diegomillan commented
@stvstnfrd I applied the requested changes.

2016-10-17 21:34 UTC, diegomillan commented on templates/theme-footer.html
> +        © ${now().strftime('%Y')} <span class="license-text">${_("Stanford Medicine")}</span>
@stvstnfrd I applied the requested changes.

2016-10-27 23:25 UTC, stvstnfrd approved these changes

2016-10-27 23:25 UTC, merged